# This file configures the Cron Job for the application.
# The job below is set to run every minute.

[cron.jobs.update_all_task_statuses]
# Tạm thời đổi lịch trình thành mỗi 2 phút để reset
schedule = "*/2 * * * *"
function = "update-task-statuses"
header.Authorization = "Bearer ${CRON_SECRET}"